services:
  db:
    image: mysql:8.0
    container_name: censo-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: censo_coahuila
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
